12: Update workflow to reduce deployment time (#13)
* Add cache layer to reduce dependencies installation time
* Fix write permission
* Adding manual workflow
* Fix cannot use secrets in workflow_dispatch
* Update packages

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -1,15 +1,49 @@
+# name of workflow
 name: Deploy Tracker App
 
+# when the workflow will be triggered
 on:
   push:
     branches:
       - main
+  workflow_dispatch:
+    inputs:
+      environment:
+        description: 'Environment'
+        required: true
+        type: choice
+        default: 'dev'
+        options:
+          - dev
+          - prod
+      config:
+        description: 'Firebase Config'
+        required: false
+        type: string
 
+# environment variables on top level, available to all jobs
+env:
+  REACT_APP_ENV: ${{ github.event.inputs.environment || 'prod' }}
+  REACT_APP_FIREBASE_CONFIG: ${{  github.event.inputs.config || secrets.REACT_APP_FIREBASE_CONFIG }}
+
+# permissions
+permissions:
+  contents: write
+
+# list of jobs in pipeline
 jobs:
   build-and-deploy:
-    runs-on: ubuntu-latest
+    # slim image boot a bit faster (not for heavy builds, docker not supported)
+    runs-on: ubuntu-slim
 
     steps:
+      - name: Check Secrets
+        run: |
+          if [ -z "$REACT_APP_FIREBASE_CONFIG" ]; then
+            echo "Failed to load Secrets"
+            exit 1
+          fi
+
       - name: Checkout code
         uses: actions/checkout@v6
 
@@ -17,22 +51,25 @@ jobs:
         uses: actions/setup-node@v6
         with:
           node-version: '24'
+          # this will cache the node_modules folder
+          # cache: 'npm'
+          # cache-dependency-path: '**/package.json'
 
+      - name: Cache node_modules
+        id: cache-npm
+        uses: actions/cache@v4
+        with:
+          path: node_modules
+          key: ${{ runner.os }}-${{ env.REACT_APP_ENV }}-build-${{ hashFiles('**/package-lock.json') }}
+
+      # Install dependencies if not updated
+      # 'npm ci' is same as 'npm install' but preferred command for CI/CD
       - name: Install dependencies
-        run: npm install
+        if: steps.cache-npm.outputs.cache-hit != 'true'
+        run: npm ci --loglevel error
 
-      - name: Check Secrets and Build the App
-        env:
-          REACT_APP_ENV: prod
-          REACT_APP_FIREBASE_CONFIG: ${{ secrets.REACT_APP_FIREBASE_CONFIG }}
-        run: |
-          if [ -z "$REACT_APP_FIREBASE_CONFIG" ]; then
-            echo "::error::Secret 'Firebase Config' is missing or empty!"
-            exit 1
-          else
-            echo "Secrets found! Building the app..."
-            npm run build
-          fi
+      - name: Build the App
+        run: npm run build
 
       - name: Deploy to GitHub Pages
         uses: peaceiris/actions-gh-pages@v4
